/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ViewLogin;

import Database.ConnectDB;
import Model.taiKhoan;
import ViewQuanLy.formQuanLy;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author LENOVO
 */
public class formLogin extends javax.swing.JFrame {

    /**
     * Creates new form formLogin
     */
    public formLogin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allPanel = new javax.swing.JPanel();
        leftPanel = new javax.swing.JPanel();
        lblImage = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblTenDN = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        gachduoi1 = new javax.swing.JTextField();
        txtTenDangNhap = new javax.swing.JTextField();
        txtMatKhau = new javax.swing.JPasswordField();
        gachduoi2 = new javax.swing.JTextField();
        btnDangNhap = new javax.swing.JButton();
        lblThoat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        allPanel.setBackground(new java.awt.Color(82, 83, 81));

        leftPanel.setBackground(new java.awt.Color(51, 153, 255));

        lblImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Res/user128.png"))); // NOI18N

        lblLogin.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(255, 255, 255));
        lblLogin.setText("LOGIN");

        javax.swing.GroupLayout leftPanelLayout = new javax.swing.GroupLayout(leftPanel);
        leftPanel.setLayout(leftPanelLayout);
        leftPanelLayout.setHorizontalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblImage)
                    .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        leftPanelLayout.setVerticalGroup(
            leftPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(lblImage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lblTenDN.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblTenDN.setForeground(new java.awt.Color(255, 255, 255));
        lblTenDN.setText("Tên đăng nhập:");

        lblMatKhau.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        lblMatKhau.setText("Mật khẩu:");

        gachduoi1.setForeground(new java.awt.Color(255, 255, 255));
        gachduoi1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        txtTenDangNhap.setBackground(new java.awt.Color(82, 83, 81));
        txtTenDangNhap.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTenDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        txtTenDangNhap.setBorder(null);

        txtMatKhau.setBackground(new java.awt.Color(82, 83, 81));
        txtMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtMatKhau.setForeground(new java.awt.Color(255, 255, 255));
        txtMatKhau.setBorder(null);

        gachduoi2.setForeground(new java.awt.Color(255, 255, 255));
        gachduoi2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        btnDangNhap.setBackground(new java.awt.Color(51, 153, 255));
        btnDangNhap.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        btnDangNhap.setForeground(new java.awt.Color(255, 255, 255));
        btnDangNhap.setText("Đăng nhập");
        btnDangNhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDangNhapActionPerformed(evt);
            }
        });

        lblThoat.setBackground(new java.awt.Color(82, 83, 81));
        lblThoat.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblThoat.setForeground(new java.awt.Color(255, 255, 255));
        lblThoat.setText("Thoát");
        lblThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout allPanelLayout = new javax.swing.GroupLayout(allPanel);
        allPanel.setLayout(allPanelLayout);
        allPanelLayout.setHorizontalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(allPanelLayout.createSequentialGroup()
                .addComponent(leftPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(allPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTenDN)
                            .addComponent(lblMatKhau)
                            .addComponent(gachduoi1)
                            .addComponent(txtTenDangNhap)
                            .addComponent(txtMatKhau)
                            .addComponent(gachduoi2)
                            .addComponent(btnDangNhap, javax.swing.GroupLayout.DEFAULT_SIZE, 264, Short.MAX_VALUE)))
                    .addGroup(allPanelLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(lblThoat)))
                .addGap(0, 50, Short.MAX_VALUE))
        );
        allPanelLayout.setVerticalGroup(
            allPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(leftPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(allPanelLayout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(lblTenDN)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gachduoi1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(lblMatKhau)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gachduoi2, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnDangNhap, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblThoat)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(allPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDangNhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDangNhapActionPerformed
//        // TODO add your handling code here:
        try {
            String tenDangNhap = txtTenDangNhap.getText().trim();
            String matKhau = new String(txtMatKhau.getPassword()).trim();

            if (tenDangNhap.isEmpty() || matKhau.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu!");
                return;
            }

            Connection conn = ConnectDB.getConnection();
            String sql = "SELECT tk.maTaiKhoan, tk.tenDangNhap, tk.matKhau, tk.loaiTaiKhoan, tk.maNhanVien, nv.tenNhanVien "
                    + "FROM taiKhoan tk LEFT JOIN NhanVien nv ON tk.maNhanVien = nv.maNhanVien "
                    + "WHERE tk.tenDangNhap = ? AND tk.matKhau = ?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1, tenDangNhap);
            pstmt.setString(2, matKhau);
            ResultSet rs = pstmt.executeQuery();

            if (rs.next()) {
                String maTaiKhoan = rs.getString("maTaiKhoan");
                String loaiTaiKhoan = rs.getString("loaiTaiKhoan").trim();
                String maNhanVien = rs.getString("maNhanVien");
                String tenNhanVien = rs.getString("tenNhanVien");

                taiKhoan tk = new taiKhoan(maTaiKhoan, tenDangNhap, matKhau, loaiTaiKhoan, maNhanVien, tenNhanVien);
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công! (Loại tài khoản: " + loaiTaiKhoan + ")");

                formQuanLy formQuanLy = new formQuanLy(tk);
                formQuanLy.setVisible(true);
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
            }

            rs.close();
            pstmt.close();
            conn.close();
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Lỗi khi đăng nhập!");
            JOptionPane.showMessageDialog(this, "Chi tiết lỗi: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDangNhapActionPerformed

    private void lblThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThoatMouseClicked
        // TODO add your handling code here:
        // Mở formTrangBatDau
        formTrangBatDau formTrangBatDau = new formTrangBatDau();
        formTrangBatDau.setVisible(true);
        // Đóng form hiện tại
        this.dispose();
    }//GEN-LAST:event_lblThoatMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formLogin().setVisible(true);
            }
        });
    }
    
    
    //        try {
//        // Lấy dữ liệu từ giao diện
//        String tenDangNhap = txtTenDangNhap.getText().trim();
//        String matKhau = new String(txtMatKhau.getPassword()).trim();
//         // Kiểm tra dữ liệu rỗng
//        if (tenDangNhap.isEmpty() || matKhau.isEmpty()) {
//            JOptionPane.showMessageDialog(this, "Vui lòng nhập đầy đủ tên đăng nhập và mật khẩu!");
//            return;
//        }
//        // Kết nối DB
//        Connection conn = ConnectDB.getConnection();
//        // Câu truy vấn kiểm tra đăng nhập
//        String sql = "SELECT tk.*, nv.tenNhanVien FROM taiKhoan tk LEFT JOIN NhanVien nv ON tk.maNhanVien = nv.maNhanVien WHERE tk.tenDangNhap = ? AND tk.matKhau = ?";
//        PreparedStatement pstmt = conn.prepareStatement(sql);
//        pstmt.setString(1, tenDangNhap);
//        pstmt.setString(2, matKhau);
//        ResultSet rs = pstmt.executeQuery();
//
//        // Kiểm tra kết quả
//        if (rs.next()) {
//            String loaiTaiKhoan = rs.getString("loaiTaiKhoan").trim();
//            JOptionPane.showMessageDialog(this, "Đăng nhập thành công! (Loại tài khoản: " + loaiTaiKhoan + ")");
//
//                
//             if (loaiTaiKhoan.equalsIgnoreCase("admin")) {
//                 formQuanLy formQuanLy = new formQuanLy("Admin");
//                 formQuanLy.setVisible(true);
//             } else {
//                 formQuanLy formQuanLy = new formQuanLy("User");
//                 formQuanLy.setVisible(true);
//             }
//
//            this.dispose();
//            
//        } else {
//            JOptionPane.showMessageDialog(this, "Sai tên đăng nhập hoặc mật khẩu!");
//        }
//
//        rs.close();
//        pstmt.close();
//        conn.close();
//
//    } catch (Exception e) {
//        e.printStackTrace();
//        JOptionPane.showMessageDialog(this, "Lỗi khi đăng nhập!");
//        JOptionPane.showMessageDialog(this, "Chi tiết lỗi: " + e.getMessage());
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allPanel;
    private javax.swing.JButton btnDangNhap;
    private javax.swing.JTextField gachduoi1;
    private javax.swing.JTextField gachduoi2;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblTenDN;
    private javax.swing.JLabel lblThoat;
    private javax.swing.JPanel leftPanel;
    private javax.swing.JPasswordField txtMatKhau;
    private javax.swing.JTextField txtTenDangNhap;
    // End of variables declaration//GEN-END:variables
}
